declare var ws: any;
declare var funcaoSucesso:any;

declare function test();

declare function cliente(porta, funcaoErroCarregamento, funcaoSucessoCarregamento);
declare function functionName();
declare function redirecionarPagina(codigoErro, razaoErro);
declare function inicializarSigner();
declare function setValidadeCert(certificado);
declare function setCertificado(index);
declare function enviarDesafio();
declare function tratarMensagem(evt);
declare function exibeCaminhoImagem(resposta);
declare function exibirBarraProgresso(visivel);
declare function tratarCertificados(resposta);
declare function tratarVersao(resposta);
declare function exibirCertificado(resposta);
declare function tratarCertificadoBase64(resposta);
declare function tratarParametro(resposta);
declare function enviarRequisicao(requisicao);
declare function tratarParametroID(resposta);
declare function setParametroID(resposta);
declare function finalizar(ok);
declare function finalizarAssinatura(resposta);
declare function listarArquivos(resposta);
declare function tratarEstatisticas(resposta);
declare function exibirAlerta(resposta);
declare function alerta(chave, msg);
declare function tratarExceptionServidor();
declare function tratarExceptionServidorTermino();
declare function exibeProgresso(resposta);
declare function exibeBarraDeProgresso(resposta);
declare function exibirProgresso(mensagem);
declare function exibirProcurar();
declare function exibirProcurarImagem();
declare function assinarWS();
declare function setPadrao(valor);
declare function solicitaCertificado();
declare function mostrarDetalhesWS();
declare function atualizarListaCertificadosWS();
declare function salvarAssinatura(assinatura);
declare function inicializaWebSocket(porta, funcaoErroCarregamento, funcaoCarregamento, funcaoSucessoCarregamento);
declare function addCertCombo(obj);
declare function carregaConteudo();
declare function calculaHash();

//declare function paraServer();
declare function exibirModal();
declare function fecharModal();
declare function findByClass(matchClass);
declare function getParametrosInit();
declare function getDateDiff(date1, date2, interval);
declare function avisoExpirar(dataValidade);
declare function selecionarAlgoritmoAssinatura(valor);
declare function selecionarOperacaoAssinatura(valor);
declare function selecionarTipoAssinatura(valor);
declare function selecionarPoliticaAssinatura(valor);
declare function retorno();
declare function selecionarPoliticaVersao(valor);
declare function setTipoAssinaturaCMS(valor);
declare function configurarPDF();
declare function test();
